# Generated by Django 4.2.4 on 2023-08-05 02:08

from django.db import migrations, models
import django.db.models.deletion


def del_address(apps, schema_editor):
    Users = apps.get_model('main', 'Users')
    Address = apps.get_model('main', 'Address')
    for user in Users.objects.all():
        address = Address.objects.get_or_create(address=user.user_address)[0]
        # print(address)
        user.user_address = address.id
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),

        migrations.RunPython(del_address),

        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.address'),
        ),
    ]
