# Generated by Django 4.2.4 on 2023-08-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.address'),
        ),
    ]
